#
# docker-compose.yml: Docker Management with Portainer contains a Docker Compose
# configuration tailored for Synology NAS environments, simplifying the setup process
# for managing Docker containers by integrating Portainer.
#
# Included Tool:
#   - Portainer: Manages Docker containers through a user-friendly web interface.
#
# For more information about Portainer, visit: https://www.portainer.io/
#

#
# Docker Compose version on the target system
#
version: "2.9"

#
# Define the services section
#
services:
  #
  # Define the 'portainer' service
  #
  portainer:
    # Docker image and container information
    image: portainer/portainer-ce:${PORTAINER_TAG} # Run using the specified tag
    pull_policy: always                            # Ensure that the image is always pulled
    container_name: portainer-${PORTAINER_TAG}     # Append Docker image tag to container name
    restart: unless-stopped                        # Restart the container unless explicitly stopped
    network_mode: bridge                           # Use the host network
    hostname: portainer                            # Set the container hostname

    # Define the host and container ports
    ports:
      - "8888:8000"
      - "9443:9443"

    # Mount host directories into the container
    volumes:
      - ${HOST_DOCKER_PATH}/portainer/data:/data:rw  # Mount data directory
      - /var/run/docker.sock:/var/run/docker.sock:rw # Allow container to talk to host Docker API
      - /etc/localtime:/etc/localtime:ro             # Setup container with the proper timezone
